version: '3.3'
services:
  db:
    image: postgres
    container_name: project-postgres
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  django:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: /start.sh
    volumes:
      - .:/app
    container_name: project-django
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
volumes:
  postgres_data: